orbs:
  sonarcloud: sonarsource/sonarcloud@2.0.0
version: 2.1
executors:
  docker-python3:
    docker:
      - image: cimg/python:3.13.2
    resource_class: medium
  docker-sonarcloud:
    docker:
      - image: cimg/node:20.8.1
    resource_class: medium
jobs:
  static-analysis:
    executor: docker-sonarcloud
    steps:
      - checkout
      - sonarcloud/scan
  build:
    executor: docker-python3
    steps:
      - checkout
      - run:
          name: Checkout git submodules
          command: |
            git submodule sync
            # git submodule update --init --recursive
            git submodule update --init
            cd pelican-themes && git submodule update --init --recursive -- blue-penguin && cd -
            cd pelican-plugins && git submodule update --init --recursive -- assets sitemap && cd -
      - restore_cache:
          keys:
            - deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
            - deps1-{{ .Branch }}-
            - deps1-
      - run:
          name: Install Python requirements
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            deactivate
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - venv
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Generate static pages
          command: |
            . venv/bin/activate
            pelican -D content -o output -s publishconf.py
            deactivate
      - store_artifacts:
          path: output
      - persist_to_workspace:
          root: .
          paths:
            - venv
            - output
  publish:
    executor: docker-python3
    steps:
      - add_ssh_keys:
          fingerprints:
            - "99:9e:01:1c:a5:16:1f:b7:6a:b8:f1:6b:b1:f6:ef:60"
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Publish static pages
          command: |
            . venv/bin/activate
            ghp-import -n output -m "[skip ci] Update of $(date)"
            git push origin gh-pages
            deactivate
workflows:
  version: 2
  build-publish:
    jobs:
      - static-analysis:
          context:
            - sonarcloud.io
          filters:
            branches:
              ignore:
                - gh-pages
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
          requires:
            - static-analysis
      - publish:
          filters:
            branches:
              only:
                - master
              ignore:
                - gh-pages
          requires:
            - build
