version: 2.1

workflows:
  post-merge:
    jobs:
      - build:
        filters:
          branches:
            ignore: gh-pages
jobs:
  build:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          name: Install requirements
          command: |
            sudo pip install -r requirements.txt
      - run:
          name: Generate static pages
          command: |
            pelican content -o output -s publishconf.py
      - store_artifacts:
          path: output
